# Declarar el contenedor de la Base de Datos
services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file: ../.env
    environment: #Seguridad y Persistencia a la Base de Datos 
      POSTGRES_USER: ${DB_USER} 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes: 
      - db_data:/var/lib/postgresql/data 
  app: #Compilar Rust desde cero dentro de un contenedor cada vez que haces un cambio es lentísimo, por eso usamos cargo watch.
    build: . #El punto (.) le dice a Docker: "Busca el archivo llamado Dockerfile que está en esta misma carpeta y úsalo para construir mi contenedor
    restart: always
    ports: #Mapea el puerto de tu servidor de Axum.
      - "${PORT}:${PORT}"
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      PORT: ${PORT}
    volumes:
      - ../../:/usr/src/app
      - cargo_cache:/usr/local/cargo/registry #Son volúmenes para que Docker guarde las dependencias descargadas de Rust y los archivos ya compilados.
      - target_cache:/usr/src/app/target
    depends_on:
      - db

volumes:
  db_data:
  cargo_cache:
  target_cache:
#volumes:: Aquí creamos el Volumen de Persistencia."Todo lo que Postgres guarde internamente en la ruta /var/lib/postgresql/data (que es donde guarda las tablas)
